### ISSUE TITLE
Association

### ISSUE THREAD

**Issue by Defman** [feather-rs/website#5]
# Assocation
## API
- Cache the budget from the association repo at `api/association/budget`
- Cache the articles of association from the association repo at `api/association/articles-of-association`
- Webhook to invalidate the cached
- Possibly add stripe payment option for membership fee

## Frontend
- Small introduction of the association at `frontend/association`
- Display the budget at `frontend/association/budget` via fetch `api/association/budget`
- Display the budget at `frontend/association/articles-of-association` via fetch `api/association/articles-of-associationt`
- Possible add stripe payment option for membership fee

**Comment by FussballAndy** [comment]
should we update the budget on a daily base or more/less frequently?

**Comment by Defman** [comment]
The budget has to be approved by the general assembly, which happens at least once a year.

**Comment by FussballAndy** [comment]
i meant how often should we update the cache to have to most recent numbers currently available in the repo and don't spam githubs servers with requests

**Comment by Defman** [comment]
Via webhooks =)

**Comment by Defman** [comment]
Maybe also add a timeout, so if we were to miss a webhook it would fix itself.
