### ISSUE TITLE
Typography

### ISSUE THREAD

**Issue by Defman** [feather-rs/website#6]
# Typography
We should have some standard `.typeography` class, with some stylying for headings, links, paragraphs, and etc. I already started some work on this in the `global.pcss`, should be moved into its own file. Feel free pull in sass, less, stylus, or alternatives.

**Comment by Defman** [comment]
Maybe a good resource could be https://design.tutsplus.com/articles/the-ultimate-guide-to-basic-typography--cms-33460

**Comment by FussballAndy** [comment]
Assign me ples, thank you
